version: "3"
services:
    shinobi:
        image: registry.gitlab.com/shinobi-systems/shinobi:dev
        container_name: Shinobi
        environment:
           - PLUGIN_KEYS={}
           - SSL_ENABLED=false
        volumes:
           - /home/azureuser/Shinobi/config:/config
           - /home/azureuser/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - /home/azureuser/Shinobi/database:/var/lib/mysql
           - /mnt/blobfuse:/home/Shinobi/videos  # Mount Azure Blob storage for video data
           - /home/azureuser/Shinobi/plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
        ports:
           - 8080:8080
        restart: unless-stopped
